In [1]:
import numpy as np 
a=np.array([2,5,7,6,0])
a


array([2, 5, 7, 6, 0])

In [2]:
type(a)


numpy.ndarray

In [3]:
import numpy as np
c=np.zeros(2)
c

array([0., 0.])

In [4]:
d=np.ones(3)
d

array([1., 1., 1.])

In [5]:
e=np.empty(4)
e

array([0.00000000e+000, 1.42744372e-311, 1.42744372e-311, 1.42744372e-311])

In [6]:
f=np.arange(2,10,2)
f


array([2, 4, 6, 8])

In [7]:
f.min()

2

In [8]:
x=np.array([2,8,1,9,4,3,7])
x

array([2, 8, 1, 9, 4, 3, 7])

In [9]:
x.sort()
x

array([1, 2, 3, 4, 7, 8, 9])

In [10]:
y=np.array([10,9,11,12])
y.sort()
y

array([ 9, 10, 11, 12])

In [11]:
np.concatenate((x,y))

array([ 1,  2,  3,  4,  7,  8,  9,  9, 10, 11, 12])

In [12]:
g=np.linspace(2,10,num=10)
g

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [13]:
h=np.ones(6, dtype=np.int16)
h

array([1, 1, 1, 1, 1, 1], dtype=int16)

In [14]:
#2D
import numpy as np 
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
c=np.array([[0,5,2,1],[7,5,8,2]])
c

array([[0, 5, 2, 1],
       [7, 5, 8, 2]])

In [16]:
np.concatenate((b,c),)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 5, 2, 1],
       [7, 5, 8, 2]])

In [17]:
e=np.concatenate((b,c), axis=1)
e

array([[1, 2, 3, 4, 0, 5, 2, 1],
       [5, 6, 7, 8, 7, 5, 8, 2]])

In [18]:
e.ndim

2

In [19]:
i=np.ones((5,6))
i

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
#3D
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
a.ndim

3

In [22]:
a.size

9

In [23]:
a.shape

(1, 3, 3)

In [24]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
a=a.reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
e=np.reshape(a, newshape=(1,16),order='c')
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [27]:
e+1


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [28]:
e.sum()

120

In [29]:
j=np.arange(1,25).reshape(2,3,4)
j

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])